version: '3.8'

services:
  frontend:
    container_name: react-frontend
    build: frontend/
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: express-server
    build: backend/
    ports:
      - 5000:5000
    depends_on:
      - postgresqldb
    
  postgresqldb:
    container_name: db
    image: postgres
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: table_db